language: python
python:
  - 2.7

notifications:
  email: false

# Install packages
install:
  - sudo apt-get install -y -qq python-dev gfortran liblapack-dev libatlas-dev build-essential libfreetype6-dev libpng-dev python-cairo
  - ln -fs /usr/lib/python2.7/dist-packages/cairo/ ~/virtualenv/python2.7/lib/python2.7/site-packages/
  - pip install numpy==1.9.1
  - pip install -r requirements.txt

before_script:
  - python manage.py syncdb --noinput
  - python manage.py make_docs
  - python manage.py load_data base_data.csv
  - python manage.py collectstatic

# Run test
script:
  - coverage run manage.py test account chem chemtools cluster data docs
