language: python
python:
  - 2.7

notifications:
  email: false

# Install packages
install:
  - bash install.sh dev

# Run test
script:
  - coverage run manage.py test account chem chemtools cluster data docs
